version: 1

# Enable to get data from 3rd-party library loggers
disable_existing_loggers: true 

formatters:
  message:
    format: "%(message)s"
  simple:
    format: "%(levelname)s: %(message)s"
  detailed:
    format: "[%(levelname)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s"

handlers:
  stdout:
    class: "logging.StreamHandler"
    formatter: "message"
    level: "INFO"
    stream: "ext://sys.stdout"
  stderr:
    class: "logging.StreamHandler"
    formatter: "simple"
    level: "WARNING"
    stream: "ext://sys.stderr"
  file:
    class: "logging.handlers.RotatingFileHandler"
    level: "DEBUG"
    formatter: "detailed"
    maxBytes: 3000000
    backupCount: 3


loggers:
  root:
    level: "INFO"
    handlers:
      - "stdout"
